
import {genConsts} from '../../utils';

export default genConsts([
  'REDDIT_CONTENT_QUERY_INDEX',
  'REDDIT_CONTENT_VIEW_MODE',
  'REDDIT_CONTENT_VIEW_MODE_CONTENT',
  'REDDIT_CONTENT_VIEW_MODE_COMMENTS',
  'REDDIT_CONTENT_IFRAME_LOADED',
], [
  'REDDIT_CONTENT_FETCH_COMMENTS',
  'REDDIT_CONTENT_FETCH_ENTRIES',
  'REDDIT_CONTENT_FETCH_MIME_TYPE',
]);

