
import {genConsts} from '../../utils';

export default genConsts([
  'REDDIT_CONTENT_QUERY_INDEX',
  'REDDIT_CONTENT_NAV_ACTIONS',
  'REDDIT_CONTENT_IFRAME_LOADED',
], [
  'REDDIT_CONTENT_FETCH_COMMENTS',
  'REDDIT_CONTENT_FETCH_ENTRIES',
]);

