
import { genConsts } from '../utils';

export default genConsts([
  'REDDIT_LOGGED_IN',
  'REDDIT_LOGIN',
  'REDDIT_QUERY_INDEX',
  'REDDIT_NAV_ACTIONS',
  'REDDIT_ENTRY_PRELOADED',
  'REDDIT_IFRAME_LOADED',
], [
  'REDDIT_FRIEND',
  'REDDIT_FETCH_COMMENTS',
  'REDDIT_LOGIN_VALIDATE',
  'REDDIT_LOAD',
  'REDDIT_FETCH_POST',
  'REDDIT_FETCH_SUBREDDITS',
  'REDDIT_FETCH_ENTRIES',
  'REDDIT_VOTE',
]);

